Repository streamnative/function-mesh, pull requests merged in 2021-07, with the labels that each got.

#226 allow set service account name for running pod
  api/v1alpha1/common.go
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  manifests/crd.yaml
Labels: doc/required

#230 fix service name observe
  controllers/function.go
  controllers/sink.go
  controllers/source.go
  controllers/spec/common.go
  controllers/spec/sink.go
Labels: type/bug

#234 fix NPE when not set AutoAck
  controllers/spec/utils.go
  controllers/spec/utils_test.go
Labels: doc/update, type/bug

#239 fix mesh worker service get status with fault pod
  charts/function-mesh-operator/crds/compute.functionmesh.io_functionmeshes.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_functions.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_sinks.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_sources.yaml
  mesh-worker-service/src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
  mesh-worker-service/src/main/java/io/functionmesh/compute/rest/api/SinksImpl.java
  mesh-worker-service/src/main/java/io/functionmesh/compute/rest/api/SourcesImpl.java
Labels: type/bug

#242 remove logTopic from connector CRD
  api/v1alpha1/sink_types.go
  api/v1alpha1/source_types.go
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/utils.go
  manifests/crd.yaml
  mesh-worker-service/src/main/java/io/functionmesh/compute/util/SinksUtil.java
  mesh-worker-service/src/main/java/io/functionmesh/compute/util/SourcesUtil.java
Labels: component/controller, doc/update, type/bug
