Repository streamnative/function-mesh, pull requests merged in 2022-08, with the labels that each got.

#437 Add a limit to the resource name
  api/v1alpha1/common.go
  api/v1alpha1/function_webhook.go
  api/v1alpha1/sink_webhook.go
  api/v1alpha1/source_webhook.go
Labels: doc-required

#439 Add sky-walking workflow for self-signed tls pulsar cluster
  .ci/clusters/values_skywalking_e2e_cluster_with_tls.yaml
  .ci/tests/integration/cases/crypto-function/manifests.yaml
  .ci/tests/integration/cases/elasticsearch-sink/manifests.yaml
  .ci/tests/integration/cases/java-download-function/manifests.yaml
  .ci/tests/integration/cases/java-function/manifests.yaml
  .ci/tests/integration/cases/mongodb-source/manifests.yaml
  .ci/tests/integration/cases/py-download-function/manifests.yaml
  .ci/tests/integration/cases/py-download-pip-function/manifests.yaml
  .ci/tests/integration/cases/py-download-zip-function/manifests.yaml
  .ci/tests/integration/e2e_with_tls.yaml
  .github/workflows/test-integration-skywalking-e2e.yml
Labels: area/ci, type/enhancement, no-need-doc, m/2022-08

#417 update CSV for openshift
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/operatorgroup.yml
  .ci/olm-tests/subs.yml
  .github/workflows/olm-verify.yml
  .github/workflows/release.yml
  .github/workflows/test-helm-charts.yml
  .github/workflows/test-integration-kind-samples.yml
  Makefile
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  hack/postprocess-bundle.sh
Labels: area/ci, type/enhancement, component/controller, no-need-doc, m/2022-08

#446 remove unnecessary step when verify OLM bundle
  .github/workflows/olm-verify.yml
Labels: area/ci, type/bug, no-need-doc, m/2022-08

#445 Add the ability to set logging levels
  .ci/tests/integration/cases/java-log-config/manifests.yaml
  .ci/tests/integration/cases/java-log-config/verify.sh
  .ci/tests/integration/cases/java-log-level/manifests.yaml
  .ci/tests/integration/cases/java-log-level/verify.sh
  .ci/tests/integration/cases/python-log-config/manifests.yaml
  .ci/tests/integration/cases/python-log-config/verify.sh
  .ci/tests/integration/cases/python-log-level/manifests.yaml
  .ci/tests/integration/cases/python-log-level/verify.sh
  .ci/tests/integration/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/test-integration-skywalking-e2e.yml
  api/v1alpha1/common.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/spec/utils.go
Labels: type/feature, component/controller, doc-required, m/2022-08

#452 add v0.5.0 changelog
  CHANGELOG.md
Labels: no-need-doc

#453 fix olm action failed when install olm
  .github/workflows/olm-verify.yml
  bump_version.sh
Labels: area/ci, type/bug, no-need-doc

#454 Update release v0.5.0 version
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc

#451 improve FunctionMesh labels
  .ci/helm.sh
  .ci/tests/integration/cases/java-log-config/verify.sh
  .ci/tests/integration/cases/java-log-level/verify.sh
  .ci/tests/integration/cases/python-log-config/verify.sh
  .ci/tests/integration/cases/python-log-level/verify.sh
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: type/enhancement, component/controller, no-need-doc, m/2022-09

#455 release 0.5.0 to openshift
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
Labels: area/ci, type/bug, doc-info-missing, m/2022-09

#459 Add integration tests for Pulsar using oauth2
  .ci/clusters/values_skywalking_e2e_cluster_with_oauth.yaml
  .ci/helm.sh
  .ci/tests/integration-oauth2/cases/java-download-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/java-download-function/verify.sh
  .ci/tests/integration-oauth2/cases/java-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/java-function/verify.sh
  .ci/tests/integration-oauth2/e2e.yaml
  .ci/tests/integration-oauth2/expected.data.yaml
  .ci/upload_function_with_oauth.sh
  .github/workflows/test-integration-skywalking-e2e.yml
Labels: area/ci, type/enhancement, no-need-doc, m/2022-09
