Repository streamnative/function-mesh, pull requests merged in 2022-10, with the labels that each got.

#477 Remove secret data
  .ci/clusters/values_skywalking_e2e_cluster_with_oauth.yaml
  .ci/tests/integration-oauth2/e2e.yaml
  .github/workflows/test-integration-skywalking-e2e.yml
Labels: area/ci, type/task, no-need-doc, m/2022-10

#478 [CVE-2020-9283 / CVE-2022-28948] resolve vulnerabilities
  go.mod
  go.sum
  images/samples/go-function-samples/func/go.mod
  images/samples/go-function-samples/func/go.sum
Labels: type/task, no-need-doc, m/2022-10

#481 fix logging window function
  .ci/helm.sh
  .ci/tests/integration-oauth2/e2e.yaml
  .ci/tests/integration/cases/elasticsearch-sink/verify.sh
  .ci/tests/integration/cases/logging-window-function/manifests.yaml
  .ci/tests/integration/cases/logging-window-function/verify.sh
  .ci/tests/integration/cases/mongodb-source/verify.sh
  .ci/tests/integration/e2e.yaml
  .ci/tests/integration/e2e_with_tls.yaml
  .github/workflows/olm-verify.yml
  images/pulsar-functions-base-runner/Dockerfile
Labels: type/bug, no-need-doc, m/2022-10

#482 release v0.7.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-required

#485 add finalizers to RBAC
  charts/function-mesh-operator/templates/controller-manager-rbac.yaml
Labels: type/bug, component/charts, no-need-doc, m/2022-11

#488 adopt openshift olm annotation
  Makefile
  hack/postprocess-bundle.sh
Labels: no-need-doc, m/2022-11, ready-to-review

#494 upgrade the k8s dependency libraries to v1.22.*.
  .ci/helm.sh
  .ci/tests/kind.yaml
  .github/workflows/olm-verify.yml
  .github/workflows/project.yml
  .github/workflows/release-note.yml
  .github/workflows/test-helm-charts.yml
  .github/workflows/test-integration-skywalking-e2e.yml
  Dockerfile
  Makefile
  PROJECT
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/templates/controller-manager-rbac.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/function_controller.go
  controllers/function_controller_test.go
  controllers/functionmesh_controller.go
  controllers/sink_controller.go
  controllers/sink_controller_test.go
  controllers/source_controller.go
  controllers/source_controller_test.go
  controllers/spec/common.go
  controllers/spec/controller_configs.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/common.sh
  install.sh
  redhat.Dockerfile
  tools/migration.go
Labels: type/enhancement, no-need-doc, m/2022-11, ready-to-review
