Repository streamnative/function-mesh, pull requests merged in 2022-03, with the labels that each got.

#331 remove unnecessary steps in kind script
  .ci/deploy_pulsar_cluster.sh
Labels: area/ci

#327 support namespace config for helm charts
  charts/function-mesh-operator/templates/controller-manager-configmap.yaml
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/templates/controller-manager-ns.yaml
  charts/function-mesh-operator/templates/controller-manager-rbac.yaml
  charts/function-mesh-operator/values.yaml
Labels: type/feature, component/charts

#329 add more useful params for manager
  main.go
Labels: type/enhancement, component/controller

#334 bump scripts version
  .github/workflows/test-helm-charts.yml
  hack/common.sh
  hack/kind-cluster-build.sh
Labels: area/ci, type/enhancement

#328 [ISSUE 315] Move apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1
  Makefile
  api/v1alpha1/function_webhook.go
  api/v1alpha1/sink_webhook.go
  api/v1alpha1/source_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/crds/compute.functionmesh.io_functionmeshes.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_functions.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_sinks.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  config/crd/patches/cainjection_in_functionmeshes.yaml
  config/crd/patches/cainjection_in_functions.yaml
  config/crd/patches/cainjection_in_sinks.yaml
  config/crd/patches/cainjection_in_sources.yaml
  config/crd/patches/webhook_in_functionmeshes.yaml
  config/crd/patches/webhook_in_functions.yaml
  config/crd/patches/webhook_in_sinks.yaml
  config/crd/patches/webhook_in_sources.yaml
  config/webhook/manifests.yaml
  manifests/crd.yaml
Labels: type/enhancement, doc/update, component/controller

#336 verify Apache Pulsar 2.10
  .ci/clusters/compute_v1alpha1_function.yaml
  .ci/clusters/compute_v1alpha1_function_builtin_hpa.yaml
  .ci/clusters/compute_v1alpha1_function_hpa.yaml
  .ci/clusters/compute_v1alpha1_functionmesh.yaml
  .ci/clusters/compute_v1alpha1_go_function.yaml
  .ci/clusters/compute_v1alpha1_py_function.yaml
  .ci/clusters/values.yaml
  .ci/clusters/values_cluster.yaml
  .ci/clusters/values_custom_runner_images.yaml
  .ci/clusters/values_runner_images.yaml
  .ci/helm.sh
  .github/workflows/test-e2e-crypto.yml
  .github/workflows/test-function-key-based-batcher.yml
  .github/workflows/test-function-runner.yml
  .github/workflows/test-integration-kind-samples.yml
  charts/function-mesh-operator/values.yaml
  controllers/spec/common.go
Labels: area/ci, type/enhancement

#335 [CI] Add doc bot
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/documentbot.yml
Labels: area/ci, type/enhancement

#337 bump to 0.1.11-rc2
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-info-missing

#338 fix github actions tool versions and release action
  .github/workflows/test-e2e-crypto.yml
  .github/workflows/test-function-key-based-batcher.yml
  .github/workflows/test-integration-kind-samples.yml
  .github/workflows/test-sink.yml
  .github/workflows/test-source.yml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  manifests/rbac.yaml
Labels: area/ci, doc-info-missing

#341 fix webhook service
  .github/workflows/test-helm-charts.yml
  .github/workflows/test-integration-kind-samples.yml
  Makefile
  api/v1alpha1/function_webhook.go
  api/v1alpha1/sink_webhook.go
  api/v1alpha1/source_webhook.go
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  license_test.go
  main.go
Labels: type/bug, doc-info-missing

#342 bump to 0.1.11-rc3
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-info-missing

#344 fix helm charts yaml format
  charts/function-mesh-operator/templates/controller-manager-configmap.yaml
Labels: type/bug, component/charts

#345 fix helm charts install
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  main.go
Labels: doc-info-missing

#343 apply istio service port name convention to function-mesh services
  config/rbac/auth_proxy_service.yaml
  config/webhook/service.yaml
  controllers/spec/common.go
  controllers/spec/utils.go
  manifests/rbac.yaml
Labels: type/enhancement, component/controller, doc-info-missing

#346 [charts] set namespace to default
  charts/function-mesh-operator/values.yaml
Labels: component/charts

#339 support more controller manager params for helm charts
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/values.yaml
  main.go
Labels: doc-info-missing
