Repository streamnative/function-mesh, pull requests merged in 2022-11, with the labels that each got.

#497 Add readme docs to helm chart
  .ci/ct.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-secrets-webhook/Chart.yaml
Labels: type/task, doc, m/2022-11, ready-to-review

#496 Add batch source config
  api/compute/v1alpha1/source_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/utils.go
  controllers/spec/utils_test.go
  manifests/crd.yaml
Labels: type/feature, doc-required, m/2022-11

#492 Migrate ClusterRole from v1beta1 to v1
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/samples/mongodb-dbz.yaml
  manifests/rbac.yaml
Labels: type/enhancement, no-need-doc, m/2022-11

#506 fix python runner oauth2
  .ci/helm.sh
  .ci/tests/integration-oauth2/cases/py-download-function-legacy/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-function-legacy/verify.sh
  .ci/tests/integration-oauth2/e2e.yaml
  images/pulsar-functions-python-runner/Dockerfile
Labels: type/bug, component/runner-images, no-need-doc, m/2022-11

#479 Support vpa
  .ci/helm.sh
  .ci/tests/integration/cases/java-function-vpa/manifests.yaml
  .ci/tests/integration/cases/java-function-vpa/verify.sh
  .ci/tests/integration/e2e.yaml
  .github/workflows/project.yml
  .github/workflows/test-helm-charts.yml
  Dockerfile
  api/compute/v1alpha1/common.go
  api/compute/v1alpha1/function_webhook.go
  api/compute/v1alpha1/sink_webhook.go
  api/compute/v1alpha1/source_webhook.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/templates/controller-manager-rbac.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  config/rbac/role.yaml
  controllers/common.go
  controllers/function.go
  controllers/function_controller.go
  controllers/function_controller_test.go
  controllers/sink.go
  controllers/sink_controller.go
  controllers/source.go
  controllers/source_controller.go
  controllers/spec/common.go
  controllers/spec/vpa.go
  controllers/spec/vpa_test.go
  controllers/suite_test.go
  controllers/test_utils_test.go
  go.mod
  go.sum
  main.go
  manifests/crd.yaml
  redhat.Dockerfile
  utils/group_version.go
Labels: type/feature, doc-required, m/2022-11

#510 enable stateful configs to connectors
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: type/enhancement, doc-required, m/2022-11, ready-to-review

#512 503: temporarily fix the protobuf conflict in run command
  Makefile
Labels: type/bug, component/controller, no-need-doc, m/2022-11

#518 upgrade OLM operator capability level to "Full Lifecycle"
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
Labels: no-need-doc, m/2022-11, ready-to-review

#517 Resolve the namespace conflict of protocol buffers package
  Dockerfile
  Makefile
  api/generated/clientset/versioned/clientset.go
  api/generated/clientset/versioned/fake/clientset_generated.go
  api/generated/clientset/versioned/fake/register.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/compute_client.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_function.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_functionmesh.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_sink.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_source.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  redhat.Dockerfile
Labels: no-need-doc, m/2022-11, ready-to-review

#515 Add a flag to enable/disable downloader
  .ci/tests/integration-oauth2/e2e_with_downloader.yaml
  .github/workflows/test-integration-skywalking-e2e.yml
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/values.yaml
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  main.go
  utils/configs.go
Labels: doc-required

#520 fix release bug
  .github/workflows/release.yml
Labels: no-need-doc

#484 Add java opts
  api/compute/v1alpha1/common.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  manifests/crd.yaml
Labels: type/feature, doc-required, m/2022-11

#523 Fix legacy authSecret and tlsSecret error
  .ci/tests/integration-oauth2/cases/py-download-function-legacy/manifests.yaml
  .ci/tests/integration-oauth2/e2e.yaml
  controllers/spec/common.go
Labels: no-need-doc

#524 release v0.8.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: no-need-doc

#527 Setup trivy scanner in ci
  .github/workflows/trivy.yml
  go.mod
  go.sum
Labels: no-need-doc

#530 change `truncate` to `>`
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  hack/gen-helm-crd-templates.sh
Labels: no-need-doc

#534 Add a validation webhook for the "spec.pulsar" field
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/function_webhook.go
  api/compute/v1alpha1/sink_webhook.go
  api/compute/v1alpha1/source_webhook.go
  api/compute/v1alpha1/validate.go
Labels: doc-required, m/2022-12, ready-to-review

#532 validate the init container with legacy auth & tls config
  .ci/tests/integration-oauth2/e2e.yaml
  .ci/tests/integration-oauth2/e2e_with_downloader.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: area/ci, type/bug, no-need-doc, m/2022-12, ready-to-review
