Repository streamnative/function-mesh, pull requests merged in 2022-05, with the labels that each got.

#365 support golang 1.18
  .github/workflows/project.yml
  .github/workflows/release.yml
  .github/workflows/test-helm-charts.yml
  Dockerfile
  controllers/function_controller_test.go
  go.mod
  go.sum
  images/samples/go-function-samples/Dockerfile
  images/samples/go-function-samples/func/go.mod
  images/samples/go-function-samples/func/go.sum
Labels: type/enhancement, doc-info-missing

#361 Use {{ .Release.Namespace }} to replace {{ .Values.installation.namespace }} in chart templates
  charts/function-mesh-operator/templates/controller-manager-configmap.yaml
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/templates/controller-manager-ns.yaml
  charts/function-mesh-operator/templates/controller-manager-rbac.yaml
Labels: component/charts, doc-required, m/2022-05

#364 Add .ci/release.sh & .ci/git.sh for auto release
  .ci/git.sh
  .ci/release.sh
Labels: area/ci, no-need-doc, m/2022-05

#367 Add .ci/release.sh & .ci/git.sh for auto release
  .ci/git.sh
  .ci/release.sh
Labels: no-need-doc

#369 Upgrade chart-releaser from 1.0.0-beta1 to 1.2.0
  hack/common.sh
Labels: no-need-doc

#370 Upgrade chart-releaser from 1.0.0-beta1 to 1.2.0
  hack/common.sh
Labels: no-need-doc

#359 #325 add State Store configs to support stateful functions in Pulsar
  .ci/clusters/compute_v1alpha1_function_stateful.yaml
  .ci/clusters/values.yaml
  .ci/verify_function_mesh.sh
  .github/workflows/test-integration-kind-samples.yml
  api/v1alpha1/common.go
  api/v1alpha1/function_types.go
  api/v1alpha1/function_webhook.go
  api/v1alpha1/validate.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/samples/compute_v1alpha1_function_stateful.yaml
  controllers/function_controller_test.go
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/function_test.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/test_utils_test.go
  manifests/crd.yaml
Labels: type/feature, doc-required, m/2022-05

#373 release v0.2.0
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_functionmeshes.yaml
  charts/function-mesh-operator/crds/compute.functionmesh.io_functions.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc, m/2022-05

#374 fix build with go 1.18
  .github/workflows/project.yml
  Makefile
Labels: doc-info-missing

#372 Upgrade alpine to 3.14
  operator.Dockerfile
Labels: type/enhancement, no-need-doc, m/2022-06
