Repository streamnative/function-mesh, pull requests merged in 2022-09, with the labels that each got.

#460 add support for window function
  api/v1alpha1/common.go
  api/v1alpha1/function_types.go
  api/v1alpha1/function_webhook.go
  api/v1alpha1/validate.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  controllers/spec/common.go
  controllers/spec/utils.go
Labels: type/feature, component/controller, doc-required, m/2022-09

#450 improve the stability of autoscaling when HPA is enabled
  api/v1alpha1/function_types.go
  api/v1alpha1/function_webhook.go
  api/v1alpha1/functionmesh_types.go
  api/v1alpha1/sink_types.go
  api/v1alpha1/sink_webhook.go
  api/v1alpha1/source_types.go
  api/v1alpha1/source_webhook.go
  api/v1alpha1/validate.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/function.go
  controllers/function_controller.go
  controllers/function_controller_test.go
  controllers/function_mesh.go
  controllers/functionmesh_controller.go
  controllers/sink.go
  controllers/sink_controller.go
  controllers/source.go
  controllers/source_controller.go
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/function_test.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/test_utils_test.go
Labels: type/enhancement, component/controller, doc-required, m/2022-09

#466 rename the metrics port name
  controllers/spec/common.go
Labels: type/bug, no-need-doc, m/2022-09

#463 support log rotation
  api/v1alpha1/common.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/function.go
Labels: doc-required

#469 make java runner use different JDK based on pulsar version
  images/build.sh
  images/pulsar-functions-base-runner/Dockerfile
Labels: component/runner-images, no-need-doc, m/2022-09

#471 Release Function Mesh 0.6.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: type/task, doc, m/2022-09

#411 Use init container to download packages and functions
  .ci/clusters/values_skywalking_e2e_cluster_with_oauth.yaml
  api/v1alpha1/function_types.go
  api/v1alpha1/sink_types.go
  api/v1alpha1/source_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  manifests/crd.yaml
Labels: type/feature, doc-required, m/2022-10
