Repository streamnative/function-mesh, pull requests merged in 2022-12, with the labels that each got.

#541 add a connector sample
  images/build.sh
  images/pulsar-functions-base-runner/Dockerfile
  images/samples/build.sh
  images/samples/pulsar-io-connector/pulsar-io-elasticsearch/Dockerfile
Labels: type/enhancement, component/runner-images, no-need-doc, m/2022-12, ready-to-review

#536 address openshift 0.8.0 changes
  .github/workflows/olm-verify.yml
  .github/workflows/release.yml
  .github/workflows/trivy.yml
  Makefile
  config/manager/kustomization.yaml
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
  hack/postprocess-bundle.sh
Labels: area/ci, type/bug, no-need-doc, m/2022-12, ready-to-review

#542 504: change samples function to make documenation steps work
  config/samples/compute_v1alpha1_function.yaml
Labels: doc-info-missing

#544 Update the FunctionMesh config example to use Docker images
  config/samples/compute_v1alpha1_functionmesh.yaml
Labels: type/task, no-need-doc, m/2022-12

#548 Bump pulsarctl image to 2.10.2.3
  controllers/spec/common.go
Labels: type/task, component/controller, no-need-doc, m/2022-12

#538 Support health check
  .ci/clusters/grpcurl-pv.yaml
  .ci/clusters/grpcurl-pvc.yaml
  .ci/tests/integration/cases/health-check/manifests.yaml
  .ci/tests/integration/cases/health-check/verify.sh
  .ci/tests/integration/e2e.yaml
  api/compute/v1alpha1/common.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/templates/grpc-health-check-installation-job.yaml
  charts/function-mesh-operator/values.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/spec/utils.go
  main.go
  utils/configs.go
Labels: type/feature, doc-required, m/2022-12

#550 Fix operator vulnerability
  go.mod
  go.sum
Labels: type/bug, no-need-doc, m/2022-12

#551 v0.9.0 changelog
  CHANGELOG.md
  README.md
Labels: area/documentation, type/task, doc, m/2022-12

#554 release v0.9.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  Makefile
  README.md
  api/generated/clientset/versioned/fake/register.go
  api/generated/clientset/versioned/scheme/register.go
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: type/task, no-need-doc, m/2022-12

#549 Add exclusivity to the BuiltinHPARule
  api/compute/v1alpha1/function_webhook.go
  api/compute/v1alpha1/validate.go
  controllers/function_controller_test.go
  controllers/spec/hpa.go
Labels: type/enhancement, component/controller, no-need-doc, m/2023-01
