Repository streamnative/function-mesh, pull requests merged in 2022-07, with the labels that each got.

#414 Use secret for trust path
  api/v1alpha1/common.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/spec/utils.go
  manifests/crd.yaml
Labels: type/feature, doc-required, m/2022-07

#423 Some small types fixed in readme and makefile
  Makefile
  README.md
Labels: type/bug, doc, m/2022-07

#420 update CI workflow
  .ci/clusters/compute_v1alpha1_function.yaml
  .ci/clusters/compute_v1alpha1_function_builtin_hpa.yaml
  .ci/clusters/compute_v1alpha1_function_hpa.yaml
  .ci/clusters/compute_v1alpha1_function_stateful.yaml
  .ci/clusters/compute_v1alpha1_functionmesh.yaml
  .ci/clusters/compute_v1alpha1_go_function.yaml
  .ci/clusters/compute_v1alpha1_py_function.yaml
  .ci/clusters/values.yaml
  .ci/clusters/values_custom_runner_images.yaml
  .ci/clusters/values_runner_images.yaml
  .ci/deploy_pulsar_cluster.sh
  .ci/helm.sh
  .ci/verify_function_mesh.sh
  .github/workflows/test-e2e-crypto.yml
  .github/workflows/test-function-key-based-batcher.yml
  .github/workflows/test-function-runner.yml
  .github/workflows/test-helm-charts.yml
  .github/workflows/test-integration-kind-samples.yml
  .github/workflows/test-sink.yml
  .github/workflows/test-source.yml
  config/samples/compute_v1alpha1_function_crypto.yaml
  config/samples/compute_v1alpha1_function_stateful.yaml
  hack/kind-cluster-build.sh
Labels: area/ci, type/enhancement, no-need-doc, m/2022-07

#424 Allow key-value Environment variable passthrouugh.
  api/v1alpha1/common.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  config/samples/compute_v1alpha1_function.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  manifests/crd.yaml
Labels: type/feature, doc/required, doc, m/2022-07

#427 use ctrl.CreateOrUpdate to apply resource
  controllers/function.go
  controllers/function_controller.go
  controllers/function_mesh.go
  controllers/sink.go
  controllers/sink_controller.go
  controllers/source.go
  controllers/source_controller.go
Labels: type/bug, no-need-doc, m/2022-07

#422 Add `make e2e` command for e2e tests based on skywalking-e2e-infra
  .ci/clusters/values_skywalking_e2e_cluster.yaml
  .ci/tests/env
  .ci/tests/integration/cases/java-function/manifests.yaml
  .ci/tests/integration/cases/java-function/verify.sh
  .ci/tests/integration/e2e.yaml
  .ci/tests/integration/expected.data.yaml
  .ci/tests/kind.yaml
  .github/workflows/test-integration-kind-samples.yml
  .github/workflows/test-integration-skywalking-e2e.yml
  Makefile
  hack/kind-cluster-configuration-gen.sh
Labels: area/ci, type/feature, no-need-doc, m/2022-07

#430 add v0.4.0 changelog
  CHANGELOG.md
Labels: no-need-doc

#429 Add tests for packages download
  .ci/clusters/values_skywalking_e2e_cluster.yaml
  .ci/examples/py-examples/exclamation.zip
  .ci/examples/py-examples/pulsarfunction-1.0.0-py3-none-any.whl
  .ci/helm.sh
  .ci/tests/integration/cases/go-download-function/manifests.yaml
  .ci/tests/integration/cases/go-download-function/verify.sh
  .ci/tests/integration/cases/java-download-function/manifests.yaml
  .ci/tests/integration/cases/java-download-function/verify.sh
  .ci/tests/integration/cases/py-download-function/manifests.yaml
  .ci/tests/integration/cases/py-download-function/verify.sh
  .ci/tests/integration/cases/py-download-pip-function/manifests.yaml
  .ci/tests/integration/cases/py-download-pip-function/verify.sh
  .ci/tests/integration/cases/py-download-zip-function/manifests.yaml
  .ci/tests/integration/cases/py-download-zip-function/verify.sh
  .ci/tests/integration/e2e.yaml
  .ci/upload_function.sh
  controllers/spec/common.go
Labels: no-need-doc

#433 Use v1.8.2 for cert-manager tests
  .ci/tests/integration/e2e.yaml
  .github/workflows/test-helm-charts.yml
  .github/workflows/test-integration-kind-samples.yml
Labels: no-need-doc

#432 Cherry-pick release v0.4.0 version
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc

#431 Add handle logic for FunctionMesh to clean up orphaned subcomponents
  .ci/helm.sh
  .ci/tests/integration/cases/reconciliation/manifests-one.yaml
  .ci/tests/integration/cases/reconciliation/manifests-two.yaml
  .ci/tests/integration/cases/reconciliation/verify.sh
  .ci/tests/integration/e2e.yaml
  .gitignore
  api/v1alpha1/common.go
  controllers/function_mesh.go
Labels: no-need-doc, m/2022-08
