Repository streamnative/function-mesh, pull requests merged in 2022-06, with the labels that each got.

#380 fix #379 fix python runner protobuf version
  images/pulsar-functions-python-runner/Dockerfile
Labels: area/ci, type/bug, component/runner-images, no-need-doc, m/2022-06

#377 Support specifying an object as unmanaged.
  controllers/function_controller.go
  controllers/functionmesh_controller.go
  controllers/sink_controller.go
  controllers/source_controller.go
  controllers/spec/common.go
Labels: doc-required, m/2022-06

#386 fix: convert the memory value to decimal format
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: type/bug, no-need-doc, m/2022-06

#387 Pass LeaderElectionNamespace when not in k8s
  main.go
Labels: no-need-doc

#392 add gp-pages readme
  .gitignore
  README.md
Labels: area/documentation, component/charts

#393 Add dockerfile to build image for red hat certification
  .github/workflows/release-note.yml
  .github/workflows/test-helm-charts.yml
  LICENSE
  Makefile
  redhat.Dockerfile
Labels: type/enhancement, no-need-doc, m/2022-06

#394 Improve the bump_version.sh script
  .github/workflows/test-helm-charts.yml
  bump_version.sh
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/certificates.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/charts/admission-webhook/values.yaml
  charts/function-mesh-operator/templates/_helpers.tpl
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/values.yaml
Labels: area/ci, type/enhancement, no-need-doc, m/2022-06

#395 Add `kustomize` before `crd` in `release` command in Makefile
  Makefile
Labels: no-need-doc

#396 remove `helm-crds` from `release` command in Makefile
  Makefile
Labels: no-need-doc

#403 add v0.3.0 changelog
  CHANGELOG.md
Labels: doc

#406 wait for controller POD ready in Github Action
  .github/workflows/test-integration-kind-samples.yml
Labels: area/ci, type/bug, no-need-doc, m/2022-07

#407 update the codeowners
  .github/CODEOWNERS
Labels: doc-info-missing

#405 Fix dockerfile comment
  redhat.Dockerfile
Labels: no-need-doc

#410 add `paths-ignore` configuration
  .github/workflows/project.yml
  .github/workflows/release-note.yml
  .github/workflows/test-e2e-crypto.yml
  .github/workflows/test-function-key-based-batcher.yml
  .github/workflows/test-function-runner.yml
  .github/workflows/test-helm-charts.yml
  .github/workflows/test-integration-kind-samples.yml
  .github/workflows/test-sink.yml
  .github/workflows/test-source.yml
Labels: area/ci, type/enhancement, no-need-doc

#398 Remove invalid caBundle in webhook patches
  config/crd/patches/webhook_in_functionmeshes.yaml
  config/crd/patches/webhook_in_functions.yaml
  config/crd/patches/webhook_in_sinks.yaml
  config/crd/patches/webhook_in_sources.yaml
Labels: type/bug, no-need-doc, m/2022-07

#409 Improve tools for generating helm chart templates
  Makefile
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  hack/gen-helm-crd-templates.sh
Labels: type/enhancement, no-need-doc, m/2022-07

#402 Remove useless omitempty
  api/v1alpha1/common.go
  api/v1alpha1/function_types.go
  api/v1alpha1/sink_types.go
  api/v1alpha1/source_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  manifests/crd.yaml
Labels: type/enhancement, no-need-doc, m/2022-07
