Repository streamnative/function-mesh, pull requests merged in 2023-08, with the labels that each got.

#675 back support autoscaling/v2beta2
  .ci/tests/kind-122.yaml
  controllers/common.go
  controllers/function.go
  controllers/function_controller.go
  controllers/sink.go
  controllers/sink_controller.go
  controllers/source.go
  controllers/source_controller.go
  controllers/spec/common.go
  controllers/suite_test.go
  main.go
  utils/group_version.go
Labels: doc-info-missing

#677 Use correct value for resources in FunctionDetails
  controllers/spec/common.go
Labels: no-need-doc

#672 remove connector catalog CRD
  api/compute/v1alpha1/connectorcatalog_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/compute_client.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/connectorcatalog.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_compute_client.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_connectorcatalog.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/generated_expansion.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_connectorcatalogs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_connectorcatalogs.yaml
  config/crd/patches/webhook_in_connectorcatalogs.yaml
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
  config/rbac/connectorcatalog_editor_role.yaml
  config/rbac/connectorcatalog_viewer_role.yaml
  config/samples/compute_v1alpha1_connectorcatalog.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  hack/gen-helm-crd-templates.sh
  main.go
  manifests/crd.yaml
  pkg/webhook/common.go
  pkg/webhook/connectorcatalog_webhook.go
Labels: type/cleanup, doc-info-missing, m/2022-09

#676 fix yaml log config filename
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: doc-info-missing

#669 Decide to whether use pulsarctl based on image name
  .ci/tests/integration-oauth2/cases/java-download-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-from-http-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-function-legacy/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-function/manifests.yaml
  .ci/tests/integration/cases/go-download-function/manifests.yaml
  .ci/tests/integration/cases/java-download-function/manifests.yaml
  .ci/tests/integration/cases/py-download-pip-function/manifests.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: no-need-doc

#673 Support using sidecar to routing pod logs to Pulsar topics
  .ci/helm.sh
  .ci/tests/integration-oauth2/cases/batch-source/manifests.yaml
  .ci/tests/integration-oauth2/cases/batch-source/verify.sh
  .ci/tests/integration-oauth2/cases/java-download-function-generic-auth/manifests.yaml
  .ci/tests/integration-oauth2/cases/java-download-function-generic-auth/verify.sh
  .ci/tests/integration-oauth2/cases/java-download-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/java-download-function/verify.sh
  .ci/tests/integration/cases/elasticsearch-sink/manifests.yaml
  .ci/tests/integration/cases/elasticsearch-sink/verify.sh
  .ci/tests/integration/cases/java-download-function/manifests.yaml
  .ci/tests/integration/cases/java-download-function/verify.sh
  .ci/tests/integration/cases/mongodb-source/manifests.yaml
  .ci/tests/integration/cases/mongodb-source/verify.sh
  .ci/tests/integration/cases/py-download-function/manifests.yaml
  .ci/tests/integration/cases/py-download-function/verify.sh
  .ci/tests/integration/e2e_with_tls.yaml
  api/compute/v1alpha1/common.go
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/spec/template/filebeat-config.yaml.tmpl
  controllers/spec/template/java-runtime-log4j.xml.tmpl
  controllers/spec/template/java-runtime-log4j.yaml.tmpl
  controllers/spec/utils.go
  pkg/webhook/function_webhook.go
  pkg/webhook/sink_webhook.go
  pkg/webhook/source_webhook.go
Labels: doc-required

#671 update CHANGELOG and README for 0.15.0 release
  CHANGELOG.md
  README.md
Labels: doc

#681 Fix yaml format log config
  .ci/helm.sh
  .ci/tests/integration-oauth2/cases/java-download-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/java-download-function/verify.sh
  .ci/tests/integration/cases/java-download-function/manifests.yaml
  .ci/tests/integration/cases/java-download-function/verify.sh
  .ci/tests/integration/cases/java-log-format-json/manifests.yaml
  .ci/tests/integration/cases/java-log-yaml/manifests.yaml
  .ci/tests/integration/cases/py-download-function/manifests.yaml
  .ci/tests/integration/cases/py-download-function/verify.sh
  .ci/tests/integration/cases/python-log-format-json/manifests.yaml
  .ci/tests/integration/e2e.yaml
  controllers/spec/common.go
  controllers/spec/template/java-runtime-log4j.yaml.tmpl
  controllers/spec/template/python-runtime-log-config.ini.tmpl
Labels: no-need-doc

#682 Use regex to check whether runner image has pulsarctl
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: no-need-doc

#683 Do not create filebeat container when log topic is not set
  controllers/spec/common.go
  pkg/webhook/function_webhook.go
  pkg/webhook/sink_webhook.go
  pkg/webhook/source_webhook.go
Labels: no-need-doc

#684 Release 0.16.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-required

#685 Update README for charts
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/README.md
Labels: no-need-doc

#686 enhance the bundle release action
  .github/workflows/bundle-release.yml
  hack/publish-rhel.sh
Labels: area/ci, type/enhancement, doc-info-missing, m/2023-08
