Repository streamnative/function-mesh, pull requests merged in 2023-10, with the labels that each got.

#698 Set -Xms and -XX:UseG1GC for java runtime
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: no-need-doc

#697 fix 0.17.0 helm docs
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-secrets-webhook/README.md
Labels: doc-info-missing, m/2023-10

#688 Support rust generic runtime
  .github/workflows/project.yml
  api/compute/v1alpha1/common.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/controller_configs.go
  controllers/spec/function.go
  go.mod
  go.sum
  manifests/crd.yaml
  pkg/webhook/function_webhook.go
Labels: doc-required

#692 memory requests and limits padding fix when requests = limits
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: doc-required, m/2023-10

#703 release v0.18.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: no-need-doc

#704 fix permission for cleanupSubscription on OLM installation
  config/rbac/role.yaml
  controllers/common.go
  controllers/function.go
  controllers/function_controller.go
  controllers/sink.go
  controllers/sink_controller.go
  controllers/source.go
  controllers/source_controller.go
Labels: type/bug, no-need-doc

#705 fix olm bundle labels
  Makefile
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
  hack/postprocess-bundle.sh
Labels: area/ci, type/bug, no-need-doc

#706 fix semver check for csv
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
Labels: area/ci, type/bug, no-need-doc
