Repository streamnative/function-mesh, pull requests merged in 2023-02, with the labels that each got.

#569 Copy pulsar-client directory when exists
  go.mod
  go.sum
  images/pulsar-functions-python-runner/Dockerfile
Labels: doc-info-missing

#571 Fix vulner
  go.mod
  go.sum
Labels: no-need-doc, m/2023-02

#570 Release v0.11.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  api/generated/clientset/versioned/fake/register.go
  api/generated/clientset/versioned/scheme/register.go
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-info-missing

#576 remove image unused deps
  Makefile
  images/pulsar-functions-base-runner/Dockerfile
Labels: type/enhancement, component/runner-images, no-need-doc

#582 add default values for minReplicas and replicas
  Makefile
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
Labels: no-need-doc

#581 update development documentation
  README.md
Labels: doc

#579 Only use SubPath when jar(py|go)Location is /pulsar/xxx.suffix
  .ci/helm.sh
  .ci/tests/integration-oauth2/cases/py-download-from-http-under-second-level-path-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-from-http-under-second-level-path-function/verify.sh
  controllers/spec/common.go
  controllers/spec/common_test.go
Labels: no-need-doc

#574 enhance pod security context and container security context
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/spec/utils.go
Labels: type/enhancement, doc-required
