Repository streamnative/function-mesh, pull requests merged in 2023-03, with the labels that each got.

#592 Set subscription type according to related parameters
  api/compute/v1alpha1/sink_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  controllers/spec/utils.go
Labels: doc-required

#590 support to scale function replicas to zero when hpa is disabled
  .ci/helm.sh
  .ci/tests/integration/cases/scale-to-zero/manifests.yaml
  .ci/tests/integration/cases/scale-to-zero/verify.sh
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  api/compute/v1alpha1/validate.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
Labels: doc-required

#587 Parse env for flags
  main.go
Labels: type/enhancement, doc-required, m/2023-03

#585 Manage builtin-connectors as CRD
  api/compute/v1alpha1/connectorcatalog_types.go
  api/compute/v1alpha1/connectorcatalog_webhook.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/compute_client.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/connectorcatalog.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_compute_client.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/fake/fake_connectorcatalog.go
  api/generated/clientset/versioned/typed/compute/v1alpha1/generated_expansion.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  config/crd/bases/compute.functionmesh.io_connectorcatalogs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_connectorcatalogs.yaml
  config/crd/patches/webhook_in_connectorcatalogs.yaml
  config/manifests/bases/function-mesh.clusterserviceversion.yaml
  config/rbac/connectorcatalog_editor_role.yaml
  config/rbac/connectorcatalog_viewer_role.yaml
  config/samples/compute_v1alpha1_connectorcatalog.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  go.mod
  hack/gen-helm-crd-templates.sh
  main.go
  manifests/crd.yaml
Labels: doc-required

#601 Verify newer k8s(1.25, 1.24, 1.23)
  README.md
Labels: no-need-doc

#604 Fix liveness probe
  .ci/clusters/grpcurl-pv.yaml
  .ci/clusters/grpcurl-pvc.yaml
  .ci/tests/integration/cases/health-check/manifests.yaml
  .ci/tests/integration/e2e.yaml
  api/compute/v1alpha1/common.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/templates/controller-manager-deployment.yaml
  charts/function-mesh-operator/templates/grpc-health-check-installation-job.yaml
  charts/function-mesh-operator/values.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  controllers/spec/utils.go
  main.go
  utils/configs.go
Labels: doc-required

#605 support for configuring multi PVs for Function
  .ci/helm.sh
  .ci/tests/integration/cases/pvc-templates/manifests.yaml
  .ci/tests/integration/cases/pvc-templates/verify.sh
  Makefile
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
Labels: doc-required

#610 Replace ConnectorCatalog.ConfigFieldDefinitions with SourceConfigFieldDefinitions and SinkConfigFieldDefinitions
  api/compute/v1alpha1/connectorcatalog_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  config/crd/bases/compute.functionmesh.io_connectorcatalogs.yaml
  config/samples/compute_v1alpha1_connectorcatalog.yaml
  manifests/crd.yaml
Labels: no-need-doc

#607 Add `ShowPreciseParallelism` filed
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/utils.go
Labels: doc-required

#613 Move webhook
  Dockerfile
  api/compute/v1alpha1/common.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  main.go
  pkg/webhook/common.go
  pkg/webhook/connectorcatalog_webhook.go
  pkg/webhook/function_webhook.go
  pkg/webhook/sink_webhook.go
  pkg/webhook/source_webhook.go
  pkg/webhook/validate.go
  redhat.Dockerfile
Labels: no-need-doc

#615 release 0.12.0-rc-1
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc

#617 release 0.12.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-info-missing

#618 release 0.12.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/README.md
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: doc-info-missing
