Repository streamnative/function-mesh, pull requests merged in 2023-05, with the labels that each got.

#628 add namespace var for webhook and crd ca secret
  charts/function-mesh-operator/charts/admission-webhook/README.md
  charts/function-mesh-operator/charts/admission-webhook/templates/admission-webhook.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/charts/admission-webhook/values.yaml
Labels: component/charts, doc, m/2023-05

#631 only trigger release action on v* tags and ignore function-mesh-* tags
  .github/workflows/release.yml
Labels: area/ci, type/bug, no-need-doc, m/2023-05

#630 Add pulsarctl to runner
  .ci/helm.sh
  .ci/tests/integration-oauth2/cases/java-download-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-from-http-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-from-http-under-second-level-path-function/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-from-http-under-second-level-path-function/verify.sh
  .ci/tests/integration-oauth2/cases/py-download-function-legacy/manifests.yaml
  .ci/tests/integration-oauth2/cases/py-download-function/manifests.yaml
  .ci/tests/integration-oauth2/e2e.yaml
  .ci/tests/integration/cases/go-download-function/manifests.yaml
  .ci/tests/integration/cases/java-download-function/manifests.yaml
  .ci/tests/integration/cases/java-download-function/verify.sh
  .ci/tests/integration/cases/py-download-pip-function/manifests.yaml
  api/compute/v1alpha1/function_types.go
  api/compute/v1alpha1/sink_types.go
  api/compute/v1alpha1/source_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/spec/common.go
  controllers/spec/common_test.go
  controllers/spec/function.go
  controllers/spec/sink.go
  controllers/spec/source.go
  images/build.sh
  images/pulsar-functions-base-runner/pulsarctl.Dockerfile
  images/pulsar-functions-go-runner/pulsarctl.Dockerfile
  images/pulsar-functions-java-runner/pulsarctl.Dockerfile
  images/pulsar-functions-python-runner/pulsarctl.Dockerfile
Labels: type/enhancement, component/runner-images, no-need-doc, m/2023-05

#637 Sync proto
  api/compute/v1alpha1/common.go
  api/compute/v1alpha1/function_types.go
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functionmeshes.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  config/crd/bases/compute.functionmesh.io_functionmeshes.yaml
  config/crd/bases/compute.functionmesh.io_functions.yaml
  config/crd/bases/compute.functionmesh.io_sinks.yaml
  config/crd/bases/compute.functionmesh.io_sources.yaml
  controllers/proto/Function.pb.go
  controllers/proto/Function.proto
  controllers/spec/common.go
  controllers/spec/utils.go
Labels: doc-required

#641 Upgrade go version
  images/samples/go-function-samples/Dockerfile
Labels: type/enhancement, no-need-doc, m/2023-05

#640 Do not do clean up resources managed by function-mesh-worker-service
  controllers/function.go
  controllers/sink.go
  controllers/source.go
  controllers/spec/common.go
Labels: no-need-doc

#639 Do not update unmodifiable fields for StatefulSet
  controllers/common.go
  controllers/function.go
  controllers/sink.go
  controllers/source.go
Labels: type/enhancement, doc-required, m/2023-05

#645 use bundle release action for operator catalog release
  .github/workflows/bundle-release.yml
  .github/workflows/release.yml
  .gitignore
Labels: area/ci, type/enhancement, doc-info-missing, m/2023-05

#646 Update bundle-release.yml
  .github/workflows/bundle-release.yml
Labels: area/ci, type/bug, no-need-doc, m/2023-05

#647 fix bundle release action
  .github/workflows/bundle-release.yml
Labels: area/ci, type/bug, doc-info-missing, m/2023-05

#648 fix openshift preflight
  .github/workflows/bundle-release.yml
Labels: area/ci, type/bug, doc-info-missing, m/2023-05

#649 fix mkdir
  .github/workflows/bundle-release.yml
Labels: area/ci, type/bug, doc-info-missing, m/2023-05

#651 fix e2e pulsar install
  .ci/helm.sh
  .ci/tests/integration-oauth2/e2e.yaml
  .ci/tests/integration-oauth2/e2e_with_downloader.yaml
  .ci/tests/integration/e2e.yaml
  .ci/tests/integration/e2e_with_tls.yaml
Labels: area/ci, doc-info-missing, m/2023-05

#650 add redhat registry login
  .github/workflows/bundle-release.yml
Labels: area/ci, doc-info-missing, m/2023-05

#652 remove openshift unused step
  .github/workflows/bundle-release.yml
Labels: area/ci, type/bug, doc-info-missing, m/2023-05

#653 release function-mesh 0.14.0
  .ci/olm-tests/catalog.yml
  .ci/olm-tests/subs.yml
  CHANGELOG.md
  Makefile
  README.md
  charts/function-mesh-operator/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/Chart.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-connectorcatalogs.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-functions.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sinks.yaml
  charts/function-mesh-operator/charts/admission-webhook/templates/crd-compute.functionmesh.io-sources.yaml
  charts/function-mesh-operator/values.yaml
  install.sh
Labels: area/ci, doc, m/2023-05
